---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html
namespace: digitalocean
name: cloud
version: "0.5.0"
readme: README.md
authors:
  - Mark Mercado (@mamercad)
  - Ari Kalfus (@artis3n)
description: DigitalOcean Ansible Collection
license_file: GPL-3.0
tags:
  - cloud
  - digitalocean
  - droplet
  - sammy
repository: https://github.com/digitalocean/ansible-collection
documentation: https://github.com/digitalocean/ansible-collection/blob/main/README.md
homepage: https://github.com/digitalocean/ansible-collection
issues: https://github.com/digitalocean/ansible-collection/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
