---
name: 📝 Documentation Report
description: Ask us about docs

body:
  - type: markdown
    attributes:
      value: >
        **Thank you for wanting to report a problem with `digitalocean.cloud`
        documentation!**

        Please fill out your suggestions below. If the problem seems
        straightforward, feel free to go ahead and
        [submit a pull request][] instead!

        > [!IMPORTANT]
        > Verify first that your issue is not [already reported on
        > GitHub][issue search].

        Also test if the latest release and main branch are affected too.

        [issue search]: ../search?q=is%3Aissue&type=issues
        [submit a pull request]: https://github.com/digitalocean/ansible-collection/blob/main/CONTRIBUTING.md

  - type: textarea
    attributes:
      label: Summary
      description: >
        Explain the problem briefly below, add suggestions to wording
        or structure.
      placeholder: >-
        I was reading the `digitalocean.cloud` documentation of version X and I'm having
        problems understanding Y. It would be very helpful if that got
        rephrased as Z.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Issue Type
      description: >
        Please select the single available option in the drop-down.

        <details>
          <summary>
            <em>Why?</em>
          </summary>


          _We will make it easier in the future, once GitHub
          supports dropdown defaults. Promise!_

        </details>

      options:
        - Documentation Report
    validations:
      required: true

  - type: input
    attributes:
      label: Component Name
      description: >
        Write the short name of the rst file, module, plugin, task or
        feature below, *use your best guess if unsure*.

      placeholder: plugins/modules/droplet.py
    validations:
      required: true

  - type: textarea
    attributes:
      label: Ansible Version
      description: >-
        Paste verbatim output from `ansible --version` below, under
        the prompt line. Please don't wrap it with triple backticks — your
        whole input will be turned into a code snippet automatically.
      render: console
      value: |
        $ ansible --version
      placeholder: |
        $ ansible --version
        ansible [core 2.11.0b4.post0]  (detached HEAD ref: refs/) last updated 2021/04/02 00:33:35 (GMT +200)
        config file = None
        configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
        ansible python module location = ~/src/github/ansible/ansible/lib/ansible
        ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
        executable location = bin/ansible
        python version = 3.9.0 (default, Oct 26 2020, 13:08:59) [GCC 10.2.0]
        jinja version = 2.11.3
        libyaml = True
    validations:
      required: true

  - type: textarea
    attributes:
      label: Configuration
      description: >-
        Paste verbatim output from `ansible-config dump --only-changed -t all` below, under the prompt line.
        Please don't wrap it with triple backticks — your
        whole input will be turned into a code snippet automatically.
      render: console
      value: |
        $ ansible-config dump --only-changed -t all
      placeholder: |
        $ ansible-config dump --only-changed -t all
        DEFAULT_GATHERING(~/src/github/ansible/ansible/ansible.cfg) = smart
        DEFAULT_HOST_LIST(~/src/github/ansible/ansible/ansible.cfg) = ['~/src/github/ansible/ansible/hosts']
        DEFAULT_VAULT_PASSWORD_FILE(~/src/github/ansible/ansible/ansible.cfg) = ~/src/github/ansible/ansible/vault/print-password.sh
    validations:
      required: true

  - type: textarea
    attributes:
      label: OS / Environment
      description: >-
        Provide all relevant information below, e.g. target OS versions,
        network device firmware, etc.
      placeholder: Ubuntu 24.04, Rocky Linux 9.3 etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Describe how this improves the documentation, e.g. before/after situation or screenshots.

        > [!TIP]
        > You can paste https://gist.github.com links for larger files.

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: |
        Read the [Ansible Code of Conduct][CoC] first.

        [CoC]: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_form--bug_report.yml
      options:
        - label: I agree to follow the Ansible Code of Conduct
          required: true
