---
name: ✨ Feature request
description: Suggest an idea for this project

body:
  - type: markdown
    attributes:
      value: >
        **Thank you for wanting to suggest a feature for `digitalocean.cloud`!**


        Verify first that your idea is not [already requested on
        GitHub][issue search].

        Also test if the `main` branch does not already implement this.

        [issue search]: ../search?q=is%3Aissue&type=issues

  - type: textarea
    attributes:
      label: Summary
      description: >
        Describe the new feature/improvement you would like briefly below.

        What's the problem this feature will solve?

        What are you trying to do, that you are unable to achieve
        with `digitalocean.cloud` as it currently stands?

        * Provide examples of real-world use cases that this would enable
        and how it solves the problem you described.

        * How do you solve this now?

        * Have you tried to work around the problem using other tools?

        * Could there be a different approach to solving this issue?

      placeholder: >-
        I am trying to do X with `digitalocean.cloud` from the `main` branch on GitHub and
        I think that implementing a feature Y would be very helpful for me and
        every other user of `digitalocean.cloud` because of Z.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Issue Type
      description: >
        Please select the single available option in the drop-down.

        <details>
          <summary>
            <em>Why?</em>
          </summary>


          _We will make it easier in the future, once GitHub
          supports dropdown defaults. Promise!_

        </details>
      options:
        - Feature Idea
    validations:
      required: true

  - type: input
    attributes:
      label: Component Name
      description: >
        Write the short name of the rst file, module, plugin, task or
        feature below, *use your best guess if unsure*.

      placeholder: droplet, one_click, domain_record, account_info, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Describe how this improves the documentation, e.g. before/after situation or screenshots.

        > [!TIP]
        > You can paste https://gist.github.com links for larger files.

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: |
        Read the [Ansible Code of Conduct][CoC] first.

        [CoC]: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_form--bug_report.yml
      options:
        - label: I agree to follow the Ansible Code of Conduct
          required: true
