---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost, -c local playbooks/account_info.yml -v

- name: Account info
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get account information
      digitalocean.cloud.account_info:

# Example task output:
# TASK [Get account information] ***********************************************
# ok: [localhost] => changed=false
#   account:
#     droplet_limit: 25
#     email: mmercado@digitalocean.com
#     email_verified: true
#     floating_ip_limit: 3
#     name: Mark Mercado
#     reserved_ip_limit: 3
#     status: active
#     status_message: ''
#     team:
#       name: FOSS
#       uuid: 3281ad4a-0092-4e6b-abd2-c7a7ed111503
#     uuid: eab13a8a-99e3-4ffd-a587-b8a7789f0090
#     volume_limit: 100
#   msg: Current account information
