---
# code: language=ansible
# Running this playbook:
# ansible-playbook -i localhost, -c local playbooks/billing_history_info.yml -v

- name: Billing history info
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get billing history information
      digitalocean.cloud.billing_history_info:

# Example task output:
# TASK [Get billing history information] ***************************************
# ok: [localhost] => changed=false
#   msg: No billing history information
