name: Pull request unit tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  test-units:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        versions:
          - ansible: stable-2.14
            python: "3.9"
          - ansible: stable-2.15
            python: "3.10"
          - ansible: stable-2.16
            python: "3.10"
          - ansible: devel
            python: "3.10"
    steps:
      - name: Perform unit testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.versions.ansible }}
          origin-python-version: ${{ matrix.versions.python }}
          target-python-version: ${{ matrix.versions.python }}
          testing-type: units
